name: Deploy
on:
  push:
    branches:
      - main    
      - github-s3-deploy #for testin'
  repository_dispatch:
    types:
      - webhook
jobs:
  deploy:
    concurrency:
      group: one-deploy-at-a-time-${{ github.workflow }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Build
        run: |
          npm ci
          npm run build
        env:
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          PREFIX_PATHS: 'true'
          SITE_SUBDIR: ${{ vars.SITE_SUBDIR }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Deploy
        uses: jonelantha/gatsby-s3-action@v1
        with:
          dest-s3-bucket: aws-rocks-here
          dest-s3-path: ${{ vars.SITE_SUBDIR }}
          cloudfront-id-to-invalidate: EOCR8YF4IQ3PZ
          cloudfront-path-to-invalidate: /${{ vars.SITE_SUBDIR }}/*

